lane :bonjour do

  UI.success "Bravo !"

  scan(
    project: "FastlaneDemo.xcodeproj",
    code_coverage: true
  )
  xcov

end

lane :deploy do
  if get_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "PetitGrigri\FaslaneExample",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
    print version
  end
end
